export const ServerSocketEvents = {
  init: 'init',
  disconnect: 'disconnect',
  newMessage: 'new-message',
  editMessage: 'edit-message',
  mention: 'mention',
  reactedToMessage: 'reacted-to-message',
  deleteReaction: 'delete-reaction',
  deleteMessage: 'delete-message',
  deleteAttachment: 'delete-attachment',
  changeActivity: 'change-activity',
  newChannel: 'new-channel',
  editChannel: 'edit-channel',
  deleteChannel: 'delete-channel',
  isTyping: 'is-typing',
  stopTyping: 'stop-typing',
};
